name: Environment Variables
on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "Hello from Env Variable"
    steps:
      - name: Display Env Var
        run: echo "MY_VARIABLE:$MY_VARIABLE"
