name: Push Events
on: 
  workflow_dispatch:
    inputs:
      param1:
        description: "Description for params1"
        required: true
        default: "Hello World"

jobs:
  run-manual-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Manual task
        run: |
          echo "Running manual task with param1: ${{github.event.inputs.param1}}"
      
        
    
 
