name: Environment Variables
on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      APP_MODE: ${{vars.APP_MODE}}
    steps:
      - name: Display Env Var
        run: echo "This is $APP_MODE mode"
